Use identifier instead of path
IsaacMarovitz/Whisky pull request #109
Opened 2023-06-15 03:17 UTC by JoshuaBrest

This is better beacuse i don't want my de instance to interfere with my real instance.

2023-06-15 03:38 UTC, JoshuaBrest commented
Please note, user will have to reinstall the GPT but their whisky packages should remain.

2023-06-15 08:35 UTC, IsaacMarovitz requested changes

2023-06-15 15:19 UTC, JoshuaBrest commented on Whisky/Utils/WineInstaller.swift
> +        return FileManager.default.fileExists(atPath: libraryFolder.path())
The .path is deprecated

2023-06-19 20:44 UTC, closed without merging

2023-06-21 09:52 UTC, JoshuaBrest commented
@IsaacMarovitz Why was this closed?

2023-06-21 09:56 UTC, JoshuaBrest commented
I will redo this with modern code.