feat: applets to quickly launch applications
IsaacMarovitz/Whisky pull request #181
Opened 2023-06-29 17:53 UTC by ohaiibuzzle

tldr the idea is that the user can launch apps they want inside the bottle without going through Whisky's UI
The implementation here uses an applet with AppleScript to launch the application directly using Whisky's Wine instead of adding something like an URL handler to Whisky (which *may* be more messy)

2023-07-03 22:25 UTC, JoshuaBrest commented
> tldr the idea is that the user can launch apps they want inside the bottle without going through Whisky's UI
> The implementation here uses an applet with AppleScript to launch the application directly using Whisky's Wine instead of adding something like an URL handler to Whisky (which _may_ be more messy)

We talked about this in discord but in my opinion, this would not be great.
 - When updating implementations with wine installation, the shortcut would not be updated.
   - This can include changing the wine paths and stuff.
  - User settings won't be saved (hud, esync) 
  - I think you mentioned this, but, because the implementation on how wine is launched differs, it can make make some apps not work
    - launch with diffrent libs and stuff

2023-07-04 12:52 UTC, ohaiibuzzle commented
> When updating implementations with wine installation, the shortcut would not be updated.  

It takes Wine from the static Whisky variables, so it will always be correct

> User settings won't be saved (hud, esync)

Those are just environment vars. They can be added.

> I think you mentioned this, but, because the implementation on how wine is launched differs, it can make make some apps not work 

Uh what? Keep in mind the way the AppleScript is internally built is exactly how Apple's shell script did it, so it's a non-issue. The libs loaded are determined by dyld, not the applets

2023-07-04 22:42 UTC, JoshuaBrest commented
> > When updating implementations with wine installation, the shortcut would not be updated.
> 
> It takes Wine from the static Whisky variables, so it will always be correct on creation

Meaning that if we change the file structure, the files won't work

> > User settings won't be saved (hud, esync)
> 
> Those are just environment vars. They can be added.

true, but i don't think you can change it because you compile the applescript.

> > I think you mentioned this, but, because the implementation on how wine is launched differs, it can make make some apps not work
> 
> Uh what? Keep in mind the way the AppleScript is internally built is exactly how Apple's shell script did it, so it's a non-issue. The libs loaded are determined by dyld, not the applets

If we change the way we launch wine, like your video, different apps could not work

2023-07-04 23:57 UTC, JoshuaBrest requested changes
I would like further discussion before this gets merged.

2023-07-05 00:02 UTC, JoshuaBrest commented on Whisky/Utils/IcnsWriter.swift
> +        // Converts a size in pixels in a range to an appropriate icon size
Before you merge this, I have a library that can do this.

2023-07-05 08:24 UTC, closed without merging