Added Turkish, Portuguese, Chinese, Japanese localizations and improv…
IsaacMarovitz/Whisky pull request #82
Opened 2023-06-10 16:38 UTC by kxdrsrt

- **Added** Turkish, Portuguese, Chinese, Japanese localizations
- **Improved** German localizations"

2023-06-10 17:25 UTC, IsaacMarovitz requested changes
We already have CN locale, German improvements should be done on Crowdin not here

2023-06-11 10:13 UTC, kxdrsrt commented
> We already have CN locale, German improvements should be done on Crowdin not here

Thank you. I changed the branch to crowding. What about the other localizations?

2023-06-11 12:37 UTC, IsaacMarovitz commented
> Thank you. I changed the branch to crowdin. What about the other localizations?

I meant remove the CN locale, and apply to German changes to the [Crowdin website](https://crowdin.com/project/whisky), and then I can move the new locales to the main branch

2023-06-11 13:01 UTC, IsaacMarovitz approved these changes

2023-06-11 13:02 UTC, merged